# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Dalv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dalv


pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD','~> 1.0.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'Masonry', '~> 1.0.2'
pod 'YYModel'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'CocoaLumberjack', '~> 2.3.0'
pod 'FLEX', :configurations => ['Debug']
pod 'ReactiveCocoa', '~> 2.5'
pod 'OpenUDID', '~> 1.0.0'
# Mob产品公共库
pod 'MOBFoundation_IDFA'
pod 'SMSSDK'
pod 'SVProgressHUD'

end
